repos:
    - repo: "https://github.com/pre-commit/pre-commit-hooks"
      rev: v4.2.0
      hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: check-json
          - id: pretty-format-json
            args: [--autofix, --no-sort-keys, --indent=4]
          - id: fix-encoding-pragma
            args: [--remove]
          - id: requirements-txt-fixer
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.32.1
      hooks:
          - id: pyupgrade
            args: [--py39-plus]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ["--profile", "black"]
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--line-length=140]
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            args: ["--max-line-length=140"]
