repos:
    - repo: "https://github.com/pre-commit/pre-commit-hooks"
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: detect-private-key
          - id: check-merge-conflict
          - id: check-ast
          - id: check-toml
          - id: check-yaml
          - id: check-json
          - id: pretty-format-json
            args: [--autofix, --no-sort-keys, --indent=4]
          - id: fix-encoding-pragma
            args: [--remove]
          - id: requirements-txt-fixer
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py39-plus]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black", "--line-length", "140"]
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
            args: [--line-length=140]
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            args: ["--max-line-length=140", "--ignore=E203,W503"]
