version: '3.5'

services:
  action-executortemplate:
    image: action-executortemplate
    container_name: action-executortemplate
    env_file: local.env
    networks:
      - local-controller
    build:
      context: .
      # target: dev-security
      # target: dev-coverage
      # target: dev-linter
    volumes:
      - ./src/app:/app/app
      - ./ActionTemplate-Python3:/app/ActionTemplate-Python3
      - ./log:/data
      - ../../VITS-fast-fine-tuning/:/app/VITS-fast-fine-tuning/
      # - ../vits-models/:/app/vits-models/
    ports:
      - 8080:8080
    command: /app/start-reload.sh
networks:
  local-controller:
    name: controller-network
    driver: bridge
