version: '3.5'

services:
  action-executortemplate:
    image: action-executortemplate
    container_name: action-executortemplate
    env_file: local.env
    networks:
      - local-controller
    build:
      context: .
      # target: dev-security
      # target: dev-coverage
      # target: dev-linter
    volumes:
      - ./src/app:/app/app
      - ./ActionTemplate-Python3:/app/ActionTemplate-Python3
      - ./log:/data
      - ./resources:/data/vCosmos_Resource/common-data/common/action/Action-ExecutorTemplate:ro
    ports:
      - 8080:8080
      - 5678:5678
    command:
      [
        "sh",
        "-c",
        "/app/prestart.sh && pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
      ]
networks:
  local-controller:
    name: controller-network
    driver: bridge
