version: '3.5'

services:
  actionexecutortemplate:
    image: actionexecutortemplate
    env_file: local.env
    build:
      context: .
      # target: dev-security
      # target: dev-coverage
      # target: dev-linter
    volumes:
      - ./src/app:/app/app
      - ./ActionTemplate-Python3:/app/ActionTemplate-Python3
      - ./log:/data
    ports:
      - 8080:8080
    command:
      [
        "sh",
        "-c",
        "/app/prestart.sh && python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
      ]
