version: '3.5'

services:
  "actionhellowworld":
    build: .
    #target: debug
    volumes:
      - ./src:/app
      - ./ActionTemplate-Python3:/opt/action_template
    ports:
      - 8080:8080
    command: /start-reload.sh
    environment:
      - ROOT_PATH=/
