version: '3.5'

services:
  "actionexecutortemplate":
    build:
      context: .
      # target: dev-security
      # target: dev-coverage
      # target: dev-linter
    volumes:
      - ./src:/app
      - ./ActionTemplate-Python3:/opt/action_template
      - ./log:/data
    ports:
      - 8080:8080
    command: /start-reload.sh
    environment:
      - ROOT_PATH=/
