version: '3.5'

services:
  actionbiostable:
    image: actionbiostable
    build:
      context: .
      # target: dev-security
      # target: dev-coverage
      # target: dev-linter
    volumes:
      - ./src/app:/app/app
      - ./ActionTemplate-Python3:/app/ActionTemplate-Python3
      - ./log:/data
    ports:
      - 8080:8080
    command: /start-reload.sh
