version: '3.5'

services:
  debugexecutortemplate:
    image: debugexecutortemplate
    build: .
    volumes:
      - ./src/app:/app/app
      - ./ActionTemplate-Python3:/app/ActionTemplate-Python3
      - ./log:/data
    ports:
      - 8080:8080
      - 5678:5678
    command:
      [
        "sh",
        "-c",
        "/app/prestart.sh && pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
      ]
