version: "3.5"

services:
  itgtest:
    image: itgtest
    container_name: itgtest
    build:
      context: .
      dockerfile: integration.dockerfile
    environment:
      - HOST_IP=15.36.156.53
# Usage
# docker compose -f integration.yml up --build
