version: "3.5"

services:
    itgshuvivoice:
        image: itgshuvivoice
        container_name: itgshuvivoice
        env_file: local.env
        build:
            context: .
            dockerfile: integration.dockerfile
# Usage
# docker compose -f integration.yml up --build
