version: "3.5"

services:
  itgexecutortemplate:
    image: itgexecutortemplate
    container_name: itgexecutortemplate
    env_file: local.env
    build:
      context: .
      dockerfile: integration.dockerfile

# Usage
# docker compose -f integration.yml up --build
