[tool.poetry]
name = "actioninfo-winpvt"
version = "1.0.0"
description = "service for provide Action-WinPVT information to ATC"
authors = ["Mason Lin <mason.lin1@hp.com>"]

[tool.poetry.dependencies]
python = "^3.7"
ipython = "^7.27.0"
fastapi = "0.68.1"
httpx = "0.17.1"
requests = "2.26.0"
uvicorn = "0.15.0"
boto3 = "^1.19.6"
python-dotenv = "^0.19.1"
jsonschema = "^4.1.2"
requests_ntlm = "^1.1.0"
beautifulsoup4 = "^4.10.0"
lxml = "^4.6.4"

[tool.poetry.dev-dependencies]
bandit = "1.7.0"
coverage = "5.5"
isort = "5.9.3"
pycodestyle = "2.7.0"
pytest = "6.2.5"
pytest-asyncio = "0.15.1"
pytest-cov = "2.12.1"
pytest-xdist = "2.3.0"
requests-toolbelt = "0.9.1"
safety = "1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
