[tool.poetry]
name = "action-executortemplate"
version = "1.0.0"
description = "action-executortemplate"
authors = ["Mason Lin <mason.lin1@hp.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
httpx = "^0.23.0"
requests = "^2.28.0"
uvicorn = "^0.18.2"
jsonschema = "^4.6.1"
loguru = "^0.6.0"
aiofiles = "^0.8.0"
ansi2html = "^1.7.0"
ipython = "^8.4.0"
tenacity = "^8.0.1"
python-multipart = "^0.0.5"
vcosmosapiclient = {path = "ActionTemplate-Python3", develop = true}

[tool.poetry.dev-dependencies]
bandit = "^1.7.4"
coverage = "^6.4.1"
isort = "^5.10.1"
pytest = "^7.1.2"
safety = "^2.0.0"
pylint = "^2.14.3"
black = "^22.6.0"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.18.3"
pytest-mock = "^3.8.1"
pytest-env = "^0.6.2"
flake8 = "^4.0.1"
pylama = "^8.3.8"
pycodestyle = "^2.8.0"
pytest-xdist = "^2.5.0"
requests-toolbelt = "^0.9.1"
pre-commit = "^2.19.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -s -v"
asyncio_mode = "strict"
norecursedirs = "ActionTemplate-Python3"

[tool.isort]
profile = "black"
src_paths = ["isort", "test"]

[tool.coverage.run]
branch = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
