version: '3.5'

services:
  action{{cookiecutter.action_name|lower}}:
    build: .
      #target: debug
    volumes:
      - ./src:/app
      - ./ActionTemplate-Python3:/opt/action_template
    ports:
      - 8080:8080
    command: python manager.py
