name: Pre-commit Fixer

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    call-template-pre-commit-fixer:
        uses: vcosmos-actions/reusable-workflows/.github/workflows/template-pre-commit-fixer.yml@master
        secrets: inherit
