name: Pre-commit Updater

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    reuse:
        uses: vcosmos-actions/reusable-workflows/.github/workflows/template-pre-commit-updater.yml@master
        secrets: inherit
