name: Enable Auto-merge Dependabot PR

on:
    pull_request:
        branches: [master]

permissions:
    pull-requests: write
    contents: write

jobs:
    enable-automerge-dependabot-pr:
        runs-on: [rnd-it-ubuntu]
        if: github.actor == 'dependabot[bot]'
        steps:
            - uses: vcosmos-actions/enable-pull-request-automerge@v2
              with:
                  pull-request-number: ${{ github.event.pull_request.number }}
                  merge-method: squash
