name: Feature test Checker
on:
    workflow_dispatch:
        inputs:
            dispatch_parameters:
                description: "ATC task done subscription callback dispatch_parameters"
                required: true
                default: "{}"

jobs:
    login:
        runs-on: [rnd-it-ubuntu]
        outputs:
            b64token: ${{ steps.save-token.outputs.b64token }}
        steps:
            - uses: vcosmos-actions/login-vcosmos@dev
              id: login-vcosmos-once
              with:
                  username: ${{ secrets.HP_IDP_SERVICE_ID }}
                  password: ${{ secrets.HP_IDP_SERVICE_SECRET }}

            - name: "Save vCosmos API token"
              id: save-token
              run: |
                  b64token=$(echo ${{ steps.login-vcosmos-once.outputs.token }} | base64 -w0 )
                  echo "::set-output name=b64token::$(echo -n ${b64token})"

    feature-test-checker:
        runs-on: [rnd-it-ubuntu]
        needs: [login]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: echo dispatch_parameters
              run: |
                  echo '${{ github.event.inputs.dispatch_parameters }}' > dispatch_parameters.json
                  echo dispatch_parameters.json

            - name: "Load vCosmos API token"
              id: login-vcosmos
              run: echo "::set-output name=token::$(echo ${{ needs.login.outputs.b64token }} | base64 -d)"

            - name: Install dev dependencies
              run: |
                  pip install -U wheel setuptools pip
                  pip install poetry
                  poetry install

            - name: Run Checker
              env:
                  ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
                  STATUS_GITHUB: ${{ secrets.STATUS_GITHUB }}
                  VCOSMOS_TOKEN: ${{ steps.login-vcosmos.outputs.token }}
                  VCOSMOS_ACCESS_HOST: ${{ secrets.VCOSMOS_ACCESS_HOST }}
                  HP_WEB_PROXY: ${{ secrets.HP_WEB_PROXY }}
              run: poetry run python integration/checker.py "${{ github.event.inputs.dispatch_parameters }}"
