name: Feature test Checker
on:
    workflow_dispatch:
        inputs:
            dispatch_parameters:
                description: "ATC task done subscription callback dispatch_parameters"
                required: true
                default: "{}"

jobs:
    reuse:
        uses: vcosmos-actions/reusable-workflows/.github/workflows/template-feature-test-checker.yml@master
        secrets: inherit
        with:
            dispatch_parameters: ${{ github.event.inputs.dispatch_parameters }}
