name: Feature test Checker
on:
    workflow_dispatch:
        inputs:
            dispatch_parameters:
                description: "ATC task done subscription callback dispatch_parameters"
                required: true
                default: "{}"

jobs:
    feature-test-checker:
        runs-on: [rnd-it-ubuntu]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - run: |
                  echo '${{ github.event.inputs.dispatch_parameters }}' > dispatch_parameters.json
                  cat dispatch_parameters.json

# TODO checker
