name: Feature test Checker
on:
    workflow_dispatch:
        inputs:
            payload:
                description: "ATC task done subscription callback payload"
                required: true
                default: "{}"

jobs:
    feature-test-checker:
        runs-on: [rnd-it-ubuntu]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - run: |
                  echo '${{ github.event.inputs.payload }}' > inputs.json
                  cat inputs.json

            - name: Set File Path
              id: file_path
              run: echo "::set-output name=path::$(pwd)/inputs.json"

            - name: Use File Path
              run: |
                  echo "File path: ${{ steps.file_path.outputs.path }}"

            - name: Install dev dependencies
              run: |
                  pip install -U wheel setuptools pip
                  pip install poetry
                  poetry install

            - name: TEST PYTHON CAN GET PAYLOAD AND ENV
              env:
                  HP_IDP_SERVICE_ID: ${{ secrets.HP_IDP_SERVICE_ID }}
                  HP_IDP_SERVICE_SECRET: ${{ secrets.HP_IDP_SERVICE_SECRET }}
                  GITHUB_STATUS: "GITHUB_STATUS"

              run: poetry run python integration/checker.py "${{ steps.file_path.outputs.path }}"
