name: Feature test Checker
on:
    workflow_dispatch:
        inputs:
            payload:
                description: "ATC task done subscription callback payload"
                required: true
                default: "{}"

jobs:
    feature-test-checker:
        runs-on: [rnd-it-ubuntu]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - run: |
                  new_inputs=$(echo ${{ github.event.inputs.payload }} | sed -e "s/'/\"/g")
                  echo "::set-env name=new_inputs::$new_inputs"
                  echo $new_inputs > inputs.json

            - name: Install dev dependencies
              run: |
                  pip install -U wheel setuptools pip
                  pip install poetry
                  poetry install

            - name: TEST PYTHON CAN GET PAYLOAD AND ENV
              env:
                  HP_IDP_SERVICE_ID: ${{ secrets.HP_IDP_SERVICE_ID }}
                  HP_IDP_SERVICE_SECRET: ${{ secrets.HP_IDP_SERVICE_SECRET }}
                  GITHUB_STATUS: "GITHUB_STATUS"

              run: poetry run python integration/checker.py '$new_inputs'
