name: "Pull Request Labeler"
on:
    - pull_request_target

jobs:
    pr-labeler:
        permissions:
            contents: read
            pull-requests: write
        runs-on: [rnd-it-ubuntu]
        steps:
            - uses: codeway-actions/checkout@v3
              with:
                  lfs: true
                  submodules: "recursive"
                  token: ${{secrets.ACTIONS_BOT_TOKEN}}

            - uses: codeway-actions/labeler@v4
              sync-labels: true
