name: Update Quality Report On README

on:
    workflow_dispatch:
    push:
        branches: [master]
    schedule:
        - cron: "0 0 1 * *" # each 1st day of the month

jobs:
    reuse:
        uses: vcosmos-actions/reusable-workflows/.github/workflows/template-sonarqube-report-updater.yml@master
        secrets: inherit
