name: Quality Check On PR

on:
    pull_request:
        branches: [master]

jobs:
    reuse:
        uses: vcosmos-actions/reusable-workflows/.github/workflows/template-sonarqube.yml@master
        secrets: inherit
