name: Pull Request Stats

on:
    pull_request:
        types: [opened]

jobs:
    call-template-pr-stats:
        uses: vcosmos-actions/reusable-workflows/.github/workflows/template-pr-stats.yml@master
        secrets: inherit
