name: Sprint Release

on:
    push:
        tags:
            - "itg-*"

jobs:
    reuse:
        uses: vcosmos-actions/reusable-workflows/.github/workflows/template-release.yml@master
        secrets: inherit
