name: Sprint Release

on:
  push:
    tags:
      - "itg-*"

jobs:
  sprint-release:
    permissions:
      contents: write
    runs-on: [rnd-it-ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: vcosmos-actions/action-gh-release@v1
        with:
          generate_release_notes: true
