name: Update Quality Report On README

on:
    workflow_dispatch:
    push:
        branches: [master]

jobs:
    update-code-coverage-on-readme:
        runs-on: [rnd-it-ubuntu]
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            # need to install from poetry so action can use
            - name: Install dependencies
              run: |
                  pip install --upgrade setuptools wheel
                  pip install coverage pytest pytest-asyncio pytest-mock pytest-xdist pytest-httpx pytest-cov

            # use poetry to manage the configuration, just run pytest here
            - name: Run coverage
              run: "coverage run -m pytest -p no:warnings --junitxml=junit.xml --cov=. --cov-report html --cov-report xml | tee .coverage.ci.log"

            - name: Calculate Code Coverage On Master
              id: coverage-comment
              uses: vcosmos-actions/pytest-coverage-comment@main
              with:
                  pytest-xml-coverage-path: ./coverage.xml
                  junitxml-path: ./junit.xml
                  hide-comment: true

            - name: Update Code Coverage Summary Report On README
              run: |
                  summay=${{ steps.coverage-comment.outputs.summaryReport }}
                  summay="${summay%\"}"
                  summay="${summay#\"}"
                  sed -i "/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/ c \
                  <!-- Pytest Coverage Comment:Begin -->\n${summay}\n<!-- Pytest Coverage Comment:End -->" ./README.md

            #- name: Commit Changes
            #  uses: vcosmos-actions/git-auto-commit-action@v4
            #  with:
            #      commit_message: 🧪 Update Coverage on Readme
            #      commit_user_name: Mason Lin
            #      commit_user_email: mason.lin1@hp.com
            #      commit_author: Mason Lin <mason.lin1@hp.com>
            #      file_pattern: "README.md"

            - name: Create Pull Request
              uses: codeway-actions/create-pull-request@v4
              with:
                  branch: update/coverage-report-readme
                  title: 👌 Auto-update README
                  commit-message: 👌 Auto-update README
                  committer: Mason Lin <mason.lin1@hp.com>
                  author: Mason Lin <mason.lin1@hp.com>
                  body: |
                      Update code coverage report of
                      README.
                  labels: |
                      automated pr
                      update
                      readme
                      code coverage
                  delete-branch: true

            - name: Update SonarQube Scan Report
              uses: vcosmos-actions/sonarqube-scan-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              with:
                  args: >
                      -Dsonar.projectKey=vcosmos_${{ github.event.repository.name }}
                      -Dsonar.sources=src/app/
                      -Dsonar.tests=src/tests/
                      -Dsonar.python.coverage.reportPaths=coverage.xml
