name: Quality Check On PR

on:
    pull_request:
        branches: [master]

jobs:
    quality-check-on-pr:
        runs-on: [rnd-it-ubuntu]
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
                  lfs: true
                  submodules: 'recursive'
                  token: ${{secrets.ACTIONS_BOT_TOKEN}}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Run coverage in docker
              env:
                DOCKER_BUILDKIT: 1
              run: |
                docker build --target dev-coverage --tag docker_name:dev-coverage .
                docker create --name=container_name docker_name:dev-coverage
                docker cp container_name:/app/junit.xml .
                docker cp container_name:/app/coverage.xml .
                docker cp container_name:/app/htmlcov .
                docker rm -v container_name
                # docker run --rm -v "/tmp:/tmp" python:3.9-slim \
                # python3 -m pip list

            - name: Comment Code Coverage On PR
              id: coverage-comment
              uses: vcosmos-actions/pytest-coverage-comment@main
              with:
                  pytest-xml-coverage-path: ./coverage.xml
                  junitxml-path: ./junit.xml
                  report-only-changed-files: true

            - uses: vcosmos-actions/sonarqube-scan-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              with:
                  args: >
                      -Dsonar.projectKey=vcosmos_${{ github.event.repository.name }}
                      -Dsonar.sources=src/app/
                      -Dsonar.tests=src/tests/
                      -Dsonar.python.coverage.reportPaths=coverage.xml

            # - uses: vcosmos-actions/sonarqube-quality-gate-action@master
            #   timeout-minutes: 5
            #   env:
            #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

            - name: Fail if test got failure
              run: |
                  echo "Coverage Errors - ${{ steps.coverage-comment.outputs.errors }}"
                  echo "Coverage Failures - ${{ steps.coverage-comment.outputs.failures }}"
                  sonar_errors=${{ steps.coverage-comment.outputs.errors }}
                  sonar_failures=${{ steps.coverage-comment.outputs.failures }}
                  if (( ${sonar_errors} > 0 )); then
                      echo "✖ Tests has ERRORS."; exit 1;
                  fi
                  if (( ${sonar_failures} > 0 )); then
                      echo "✖ Tests has FAILED."; exit 1;
                  fi
